# Generated by Django 5.0.2 on 2024-03-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0002_addsuite'),
    ]

    operations = [
        migrations.CreateModel(
            name='addtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('emailid', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('nooftables', models.CharField(max_length=200)),
                ('datetime', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
