# Generated by Django 5.0.2 on 2024-03-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0003_addtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='addvenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('timein', models.CharField(max_length=200)),
                ('dateout', models.CharField(max_length=200)),
                ('timeout', models.CharField(max_length=200)),
            ],
        ),
    ]
