# Generated by Django 5.0.2 on 2024-03-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0004_addvenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtable',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='addtable',
            name='nooftables',
        ),
        migrations.RemoveField(
            model_name='addtable',
            name='venue',
        ),
    ]
