# Generated by Django 5.0.2 on 2024-03-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0005_remove_addtable_datetime_remove_addtable_nooftables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsuite',
            name='checkindate',
            field=models.DateField(null=True),
        ),
    ]
