# Generated by Django 5.0.2 on 2024-03-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0006_addsuite_checkindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsuite',
            name='checkoutdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='addsuite',
            name='checkouttime',
            field=models.TimeField(null=True),
        ),
    ]
