# Generated by Django 5.0.2 on 2024-03-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0007_addsuite_checkoutdate_addsuite_checkouttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsuite',
            name='checkintime',
            field=models.TimeField(null=True),
        ),
    ]
