# Generated by Django 5.0.2 on 2024-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0008_addsuite_checkintime'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsuite',
            name='numberofrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='addsuite',
            name='roomtype',
            field=models.IntegerField(null=True),
        ),
    ]
