# Generated by Django 5.0.2 on 2024-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0009_addsuite_numberofrooms_addsuite_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtable',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='addtable',
            name='nooftables',
            field=models.IntegerField(null=True),
        ),
    ]
