# Generated by Django 5.0.2 on 2024-03-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0010_addtable_datetime_addtable_nooftables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvenue',
            name='venue',
        ),
        migrations.AlterField(
            model_name='addvenue',
            name='contact',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addvenue',
            name='date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addvenue',
            name='dateout',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addvenue',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addvenue',
            name='timein',
            field=models.TimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addvenue',
            name='timeout',
            field=models.TimeField(max_length=200),
        ),
    ]
