# Generated by Django 5.0.2 on 2024-03-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0011_remove_addvenue_venue_alter_addvenue_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvenue',
            name='contact',
            field=models.BigIntegerField(max_length=200),
        ),
    ]
