# Generated by Django 5.0.2 on 2024-03-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0013_alter_addvenue_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvenue',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
