# Generated by Django 5.0.2 on 2024-03-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0014_alter_addvenue_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsuite',
            name='roomtype',
            field=models.CharField(choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2')], max_length=10, null=True),
        ),
    ]
