# Generated by Django 5.0.2 on 2024-03-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0015_alter_addsuite_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsuite',
            name='numberofrooms',
            field=models.SmallIntegerField(null=True),
        ),
    ]
