# Generated by Django 5.0.2 on 2024-03-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0016_alter_addsuite_numberofrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addsuite',
            name='numberofrooms',
        ),
        migrations.AlterField(
            model_name='addsuite',
            name='roomtype',
            field=models.CharField(choices=[('choice1', 'Choice 1'), ('choice2', 'Choice 2'), ('choice3', 'Choice 3')], max_length=10, null=True),
        ),
    ]
