# Generated by Django 5.0.2 on 2024-03-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0017_remove_addsuite_numberofrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsuite',
            name='roomtype',
            field=models.CharField(choices=[('Executive Rooms (8500 INR)', 'Choice 1'), ('Family Rooms(10500 INR)', 'Choice 2'), ('Pool Suite (11500 INR)', 'Choice 3')], max_length=200, null=True),
        ),
    ]
