# Generated by Django 5.0.2 on 2024-03-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0018_alter_addsuite_roomtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addsuite',
            name='checkintime',
        ),
        migrations.RemoveField(
            model_name='addsuite',
            name='checkouttime',
        ),
    ]
