# Generated by Django 5.0.2 on 2024-03-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0020_alter_addsuite_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvenue',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='addvenue',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
