# Generated by Django 5.0.2 on 2024-03-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0021_alter_addvenue_contact_alter_addvenue_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvenue',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='addvenue',
            name='dateout',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='addvenue',
            name='timein',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='addvenue',
            name='timeout',
            field=models.TimeField(null=True),
        ),
    ]
