# Generated by Django 5.0.2 on 2024-03-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0022_alter_addvenue_date_alter_addvenue_dateout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsuite',
            name='numberofrooms',
            field=models.IntegerField(null=True),
        ),
    ]
