# Generated by Django 5.0.2 on 2024-03-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0023_addsuite_numberofrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addsuite',
            name='numberofrooms',
        ),
        migrations.AlterField(
            model_name='addsuite',
            name='roomtype',
            field=models.IntegerField(null=True),
        ),
    ]
