# Generated by Django 5.0.2 on 2024-03-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0024_remove_addsuite_numberofrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsuite',
            name='roomtype',
            field=models.CharField(choices=[('Executive Rooms (8500 INR)', 'Executive Rooms (8500 INR)'), ('Family Rooms(10500 INR)', 'Family Rooms(10500 INR)'), ('Pool Suite (11500 INR)', 'Pool Suite (11500 INR)')], max_length=200, null=True),
        ),
    ]
