# Generated by Django 5.0.2 on 2024-03-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0026_alter_addsuite_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsuite',
            name='roomtype',
            field=models.IntegerField(choices=[('Executive Rooms (8500 INR)', 'Executive Rooms (8500 INR)'), ('Family Rooms(10500 INR)', 'Family Rooms(10500 INR)'), ('Pool Suite (11500 INR)', 'Pool Suite (11500 INR)')], null=True),
        ),
    ]
