# Generated by Django 5.0.2 on 2024-03-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0029_alter_addsuite_roomtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvenue',
            name='date',
        ),
        migrations.RemoveField(
            model_name='addvenue',
            name='dateout',
        ),
        migrations.RemoveField(
            model_name='addvenue',
            name='timein',
        ),
        migrations.RemoveField(
            model_name='addvenue',
            name='timeout',
        ),
        migrations.AlterField(
            model_name='addvenue',
            name='contact',
            field=models.CharField(max_length=200),
        ),
    ]
