# Generated by Django 5.0.2 on 2024-03-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0030_remove_addvenue_date_remove_addvenue_dateout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvenue',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='addvenue',
            name='dateout',
            field=models.DateField(null=True),
        ),
    ]
