# Generated by Django 5.0.2 on 2024-03-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0031_addvenue_date_addvenue_dateout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvenue',
            name='date',
        ),
        migrations.RemoveField(
            model_name='addvenue',
            name='dateout',
        ),
    ]
