# Generated by Django 5.0.2 on 2024-03-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0033_addvenue_date_addvenue_dateout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvenue',
            old_name='dateout',
            new_name='dateOut',
        ),
    ]
