# Generated by Django 5.0.2 on 2024-03-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0035_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsuite',
            name='roomtype',
            field=models.IntegerField(null=True),
        ),
    ]
