# Generated by Django 5.0.2 on 2024-03-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0037_alter_addsuite_roomtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvenue',
            old_name='date',
            new_name='checkindate',
        ),
        migrations.RenameField(
            model_name='addvenue',
            old_name='dateOut',
            new_name='checkoutdate',
        ),
    ]
