# Generated by Django 5.0.2 on 2024-03-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0038_rename_date_addvenue_checkindate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsuite',
            name='checkintime',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='addsuite',
            name='checkouttime',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
