# Generated by Django 5.0.2 on 2024-03-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0039_addsuite_checkintime_addsuite_checkouttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtable',
            name='datetime',
        ),
        migrations.AddField(
            model_name='addtable',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='addtable',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addtable',
            name='nooftables',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
