# Generated by Django 5.0.2 on 2024-03-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0040_remove_addtable_datetime_addtable_date_addtable_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtable',
            name='date',
        ),
        migrations.RemoveField(
            model_name='addtable',
            name='message',
        ),
        migrations.RemoveField(
            model_name='addtable',
            name='nooftables',
        ),
        migrations.RemoveField(
            model_name='addtable',
            name='time',
        ),
    ]
