# Generated by Django 5.0.2 on 2024-03-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0041_remove_addtable_date_remove_addtable_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvenue',
            name='checkindate',
        ),
        migrations.RemoveField(
            model_name='addvenue',
            name='checkoutdate',
        ),
    ]
