# Generated by Django 5.0.2 on 2024-03-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0042_remove_addvenue_checkindate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvenue',
            name='email',
        ),
    ]
