# Generated by Django 5.0.2 on 2024-03-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0044_addvenue_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtable',
            old_name='emailid',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='addvenue',
            name='email',
        ),
        migrations.AddField(
            model_name='addtable',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
