# Generated by Django 5.0.2 on 2024-03-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0045_rename_emailid_addtable_email_remove_addvenue_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtable',
            name='nooftables',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
