# Generated by Django 5.0.2 on 2024-03-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0046_addtable_nooftables'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtable',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
