# Generated by Django 5.0.2 on 2024-03-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0047_addtable_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtable',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
