# Generated by Django 5.0.2 on 2024-03-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0049_addvenue_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvenue',
            name='email',
        ),
    ]
