# Generated by Django 5.0.2 on 2024-03-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0050_remove_addvenue_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvenue',
            name='checkindate',
            field=models.DateField(null=True),
        ),
    ]
