# Generated by Django 5.0.2 on 2024-03-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0051_addvenue_checkindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvenue',
            name='checkoutdate',
            field=models.DateField(null=True),
        ),
    ]
