# Generated by Django 5.0.2 on 2024-03-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortbkdapp', '0052_addvenue_checkoutdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvenue',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
